### ISSUE TITLE
Time bar is no longer rainbow :(

### ISSUE THREAD

**Issue by Leah96xxx** [fzramos/nyan-ff-addon#2]
I just noticed today that the time bar is no longer rainbow. Nyan Cat is still there, but the bar is just a red-pink gradient now.
It seems to happen on every video, but _sometimes_ the rainbow will appear, though I've only been able to get it to appear by chance or in Private Mode. I've tried disabling all conflicting extensions, restarting the browser and clearing the cache, but that makes no difference.

My browser is Floorp 11.19.1

![image](https://github.com/user-attachments/assets/f7bffb39-cb17-4f29-8789-473260a6372a)

**Comment by Corgi-Senpai09** [comment]
I’m also experiencing this issue as well. I opened YouTube today and the time bar was also a red gradient instead of rainbow :( .

**Comment by fzramos** [comment]
@Leah96xxx @Corgi-Senpai09 Thank you for reporting this issue, I have updated the source code to address the issue! And I submitted the updated add-on to Mozilla. If the add-on isn't updated automatically on your browser, you can go to "about:addons" and get the update it manually.
